(function(){'use strict';
var cfg=window.IWP_SITE_CONFIG||{},appUrl=String(cfg.appUrl||''),sessionKey='iwpOrganizerSessionV1',params=new URLSearchParams(location.search),eventId=params.get('id')||'',task=params.get('task')||'Organizer Reminder',request=0,timer=0,data=null;
function byId(id){return document.getElementById(id)}function text(id,v){var e=byId(id);if(e)e.textContent=v==null?'':String(v)}function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function storageAreas(){var out=[];try{if(window.sessionStorage)out.push(window.sessionStorage)}catch(e){}try{if(window.localStorage)out.push(window.localStorage)}catch(e){}return out}
function normalizeSession(x){return x&&x.token&&x.expiresAt&&!isNaN(Date.parse(x.expiresAt))&&Date.parse(x.expiresAt)>Date.now()?{token:String(x.token),expiresAt:String(x.expiresAt),user:x.user||{}}:null}
function importSessionHandoff(){var raw=String(location.hash||'').replace(/^#/,'');if(!raw)return null;var hp=new URLSearchParams(raw),token=hp.get('session')||'',expiresAt=hp.get('expiresAt')||'',session=normalizeSession({token:token,expiresAt:expiresAt});if(!session)return null;var encoded=JSON.stringify(session);storageAreas().forEach(function(area){try{area.setItem(sessionKey,encoded)}catch(e){}});history.replaceState(null,'',location.pathname+location.search);return session}
function readSession(){var handed=importSessionHandoff();if(handed)return handed;var areas=storageAreas();for(var i=0;i<areas.length;i++){try{var x=normalizeSession(JSON.parse(areas[i].getItem(sessionKey)||'null'));if(x)return x}catch(e){}}return null}
function state(name){byId('emailLoading').hidden=name!=='loading';byId('emailAccess').hidden=name!=='access';byId('emailWorkspace').hidden=name!=='workspace'}
function fail(msg){clearTimeout(timer);state('access');text('emailAccessMessage',msg||'Return to the Organizer Command Center and sign in.')}
function jsonp(route,callback,extra){var session=readSession();if(!session){fail();return}var s=document.createElement('script');s.id='emailApi'+(++request);var q='api='+encodeURIComponent(route)+'&callback='+encodeURIComponent(callback)+'&session='+encodeURIComponent(session.token)+'&eventId='+encodeURIComponent(eventId);Object.keys(extra||{}).forEach(function(k){q+='&'+encodeURIComponent(k)+'='+encodeURIComponent(extra[k])});s.src=appUrl+(appUrl.indexOf('?')<0?'?':'&')+q+'&_='+Date.now();s.onerror=function(){fail('Unable to reach the organizer email service.')};document.head.appendChild(s);timer=setTimeout(function(){fail('The organizer email service took too long to respond.')},45000)}
function details(e){var lines=[];if(e.startDate||e.StartDate)lines.push('Date: '+(e.startDate||e.StartDate)+(e.startTime||e.StartTime?' at '+(e.startTime||e.StartTime):''));if(e.location||e.LocationName)lines.push('Location: '+(e.location||e.LocationName));if(e.address||e.Address)lines.push('Address: '+(e.address||e.Address));return lines.join('\n')}
function defaultMessage(e){var title=e.title||e.Title||'Community Connections Adventure',label=task.toLowerCase(),lead=label.indexOf('30-day')>=0?'This is an early planning update':label.indexOf('two-week')>=0?'This is your two-week reminder':label.indexOf('one-week')>=0?'This is your one-week reminder':label.indexOf('three-day')>=0?'This is your three-day reminder':label.indexOf('24-hour')>=0?'This is your reminder for tomorrow':'Here is an important event reminder';return {subject:task+': '+title,body:['Hello,','',lead+' for '+title+'.','',details(e),'','[Add any updates, meetup instructions, weather information, or items participants should bring.]','','Please contact the organizer if your plans have changed.','','You Are Not Alone.','IWP Community Connections'].join('\n')}}
function countsForAudience(){if(!data)return 0;var a=byId('emailAudience').value,c=data.counts||{};return Number(c[a]||0)}function updateCount(){text('emailRecipientBadge',countsForAudience()+' recipient'+(countsForAudience()===1?'':'s'))}
window.iwpOrganizerEmailDataCallback=function(p){clearTimeout(timer);if(!p||!p.success){var message=p&&p.error||'Unable to load email details.';if(/session|sign in|authorized|authorization|expired/i.test(message)){fail(message);return}state('workspace');text('emailPageHeading','Unable to load reminder');text('emailStatus',message);byId('sendEmailButton').disabled=true;return}data=p.data||{};var e=data.event||{},draft=defaultMessage(e);text('emailTaskLabel',task);text('emailEventTitle',e.title||e.Title||'Adventure');text('emailPageHeading',task);byId('emailSubject').value=draft.subject;byId('emailBody').value=draft.body;renderHistory(data.history||[]);state('workspace');updateCount()};
function renderHistory(items){var el=byId('emailHistory');if(!items.length){el.innerHTML='<div class="organizer-empty">No emails have been sent for this event.</div>';return}el.innerHTML=items.map(function(x){return '<div class="organizer-email-history-item"><strong>'+esc(x.subject)+'</strong><p>'+esc(x.sent)+' sent'+(x.failed?' · '+esc(x.failed)+' failed':'')+'</p><small>'+esc(x.sentAt)+(x.sentBy?' · '+esc(x.sentBy):'')+'</small></div>'}).join('')}
byId('emailAudience').addEventListener('change',updateCount);byId('sendEmailButton').addEventListener('click',async function(){var session=readSession(),subject=byId('emailSubject').value.trim(),body=byId('emailBody').value.trim(),audience=byId('emailAudience').value;if(!session){fail();return}if(!subject||!body){text('emailStatus','Enter both a subject and message.');return}var count=countsForAudience();if(!count){text('emailStatus','There are no email addresses in the selected audience.');return}if(!confirm('Send this message to '+count+' recipient'+(count===1?'':'s')+'?'))return;var b=this;b.disabled=true;b.textContent='Sending…';text('emailStatus','Sending reminder…');try{var r=await fetch('/api/organizer-email-send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({appUrl:appUrl,session:session.token,eventId:eventId,subject:subject,body:body,audience:audience,taskLabel:task})});var result=await r.json();if(!r.ok||!result.success)throw new Error(result.error||'Email could not be sent.');text('emailStatus',result.message||'Reminder sent.');b.textContent='Sent';setTimeout(function(){location.href='/organizer.html?emailSent=1'},900)}catch(e){text('emailStatus',e.message||'Email could not be sent.');b.disabled=false;b.textContent='Send Reminder'}});
if(!eventId||!appUrl){fail('The event or organizer service is missing.')}else jsonp('organizer-email-data','iwpOrganizerEmailDataCallback',{});
})();