(function(){'use strict';
var cfg=window.IWP_SITE_CONFIG||{},appUrl=String(cfg.appUrl||''),sessionKey='iwpOrganizerSessionV1',params=new URLSearchParams(location.search),eventId=params.get('eventId')||'',registrationId=params.get('registrationId')||'',token=params.get('token')||'',request=0,timer=0,data=null;
function byId(id){return document.getElementById(id)}function text(id,v){var e=byId(id);if(e)e.textContent=v==null?'':String(v)}
function areas(){var a=[];try{a.push(sessionStorage)}catch(e){}try{a.push(localStorage)}catch(e){}return a}
function readSession(){for(var i=0;i<areas().length;i++){try{var s=JSON.parse(areas()[i].getItem(sessionKey)||'null');if(s&&s.token&&s.expiresAt&&Date.parse(s.expiresAt)>Date.now())return s}catch(e){}}return null}
function state(name){byId('qrCheckInLoading').hidden=name!=='loading';byId('qrCheckInAccess').hidden=name!=='access';byId('qrCheckInWorkspace').hidden=name!=='workspace'}
function fail(msg){clearTimeout(timer);state('access');text('qrCheckInAccessMessage',msg||'Sign into the Organizer Command Center on this phone, then scan the QR code again.')}
function load(){var session=readSession();if(!session){fail();return}var s=document.createElement('script');s.id='qrCheckInApi'+(++request);s.src=appUrl+(appUrl.indexOf('?')<0?'?':'&')+'api=organizer-checkin-data&callback=iwpOrganizerQrCheckInCallback&session='+encodeURIComponent(session.token)+'&eventId='+encodeURIComponent(eventId)+'&registrationId='+encodeURIComponent(registrationId)+'&token='+encodeURIComponent(token)+'&_='+Date.now();s.onerror=function(){fail('Unable to reach the organizer check-in service.')};document.head.appendChild(s);timer=setTimeout(function(){fail('The organizer check-in service took too long to respond.')},45000)}
function render(){var e=data.event||{},r=data.registration||{},people=Number(r.adults||0)+Number(r.children||0);text('qrParticipantName',r.name||'Participant');text('qrAdventureName',e.Title||e.title||'Adventure');text('qrPartyTotal',people+' '+(people===1?'person':'people'));text('qrPartyDetails',(r.adults||0)+' adult'+(Number(r.adults||0)===1?'':'s')+(Number(r.children||0)?' · '+r.children+' child'+(Number(r.children)===1?'':'ren'):''));var guests=[];if(r.adultGuestNames)guests.push('Adult guests:\n'+r.adultGuestNames);if(r.childNames)guests.push('Children:\n'+r.childNames);byId('qrGuestNames').hidden=!guests.length;text('qrGuestNames',guests.join('\n\n'));var checked=String(r.status||'').toLowerCase()==='checked in';text('qrCurrentStatus',checked?'Already Checked In':r.status||'Confirmed');byId('qrCheckInButton').textContent=checked?'Checked In — Undo Check-In':'Check In Entire Party';byId('qrCheckInButton').classList.toggle('checked',checked);byId('qrBackToList').href='/organizer-registrations.html?id='+encodeURIComponent(eventId)+'&mode=checkin';state('workspace')}
window.iwpOrganizerQrCheckInCallback=function(p){clearTimeout(timer);if(!p||!p.success){var m=p&&p.error||'Unable to load QR check-in.';if(/session|sign in|expired|authorized/i.test(m)){fail(m);return}state('workspace');text('qrParticipantName','Unable to Check In');text('qrCheckInMessage',m);byId('qrCheckInButton').hidden=true;return}data=p.data||{};render()};
byId('qrCheckInButton').addEventListener('click',async function(){var session=readSession();if(!session){fail();return}var checked=String(data.registration.status||'').toLowerCase()==='checked in',action=checked?'undo-checkin':'checkin',button=this;button.disabled=true;button.textContent=checked?'Removing check-in…':'Checking in party…';text('qrCheckInMessage','Saving check-in…');try{var response=await fetch('/api/organizer-registration-action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({appUrl:appUrl,session:session.token,eventId:eventId,registrationIds:[registrationId],registrationAction:action,changes:{}})});var result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||'Check-in failed.');data.registration.status=checked?'Confirmed':'Checked In';render();text('qrCheckInMessage',checked?'Check-in removed.':'Party checked in successfully.');window.IWPToast&&window.IWPToast(checked?'Check-in removed.':'Party checked in successfully.','success')}catch(e){text('qrCheckInMessage',e.message||'Check-in failed.');window.IWPToast&&window.IWPToast(e.message||'Check-in failed.','error')}finally{button.disabled=false}});
if(!appUrl||!eventId||!registrationId||!token)fail('This check-in link is incomplete or invalid.');else load();
})();