(function(){'use strict';
var cfg=window.IWP_SITE_CONFIG||{},root=document.getElementById('registrationRoot'),eventId=new URLSearchParams(location.search).get('id'),current={};
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function bool(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'} function val(id){var e=document.getElementById(id);return e?String(e.value||'').trim():''} function chk(id){var e=document.getElementById(id);return !!(e&&e.checked)}
function dateKey(v){var m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?m[1]+'-'+m[2]+'-'+m[3]:''} function pretty(k){var d=new Date(k+'T12:00:00');return isNaN(d)?k:d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}
function dateRange(e){var a=dateKey(e.StartDate),b=dateKey(e.EndDate||e.StartDate);if(!a)return'Date coming soon';return pretty(a)+(b&&b!==a?' – '+pretty(b):'')}
function time(v){var m=String(v||'').match(/^(\d{1,2}):(\d{2})/);if(!m)return v||'';var h=+m[1],s=h>=12?'PM':'AM';return(h%12||12)+':'+m[2]+' '+s}
function cost(e){if(bool(e.FreeEvent))return'Free';if(bool(e.VariableCost))return e.CostDetails||'Cost varies';return e.AdultCost?'$'+String(e.AdultCost).replace(/^\$/,''):'See adventure details'}
function image(u){u=String(u||'');var m=u.match(/drive\.google\.com\/(?:file\/d\/|open\?id=|uc\?[^#]*[?&]id=)([-_a-zA-Z0-9]+)/i);return m?'https://drive.google.com/thumbnail?id='+encodeURIComponent(m[1])+'&sz=w1400':u}
function lines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function attendanceOptions(e){var a=[];if(bool(e.AllowOrganizerProvidedAccommodation))a.push(['Organizer-Provided','Organizer-provided accommodation']);if(bool(e.AllowBringOwnAccommodation))a.push(['Bring My Own','Bringing my own accommodation']);if(bool(e.AllowParticipantReservedAccommodation))a.push(['Participant Reserved','Reserved my own accommodation']);if(bool(e.AllowDayVisitors))a.push(['Day Visitor','Visiting for the day']);return a}
function resources(e){return (e.Resources||[]).filter(r=>bool(r.ReservationRequired)&&String(r.Active).toLowerCase()!=='false')}
function periods(r,e){var behavior=String(r.ReservationBehavior||'Event Day');if(behavior==='Time Slot')return String(r.TimeSlots||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);var a=dateKey(r.AvailableStartDate||e.StartDate),b=dateKey(r.AvailableEndDate||e.EndDate||e.StartDate),out=[],d=new Date(a+'T12:00:00'),end=new Date(b+'T12:00:00');while(a&&b&&d<=end&&out.length<370){var k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');if(!(behavior==='Night'&&k===b))out.push(k);d.setDate(d.getDate()+1)}return out}
function render(payload){if(!payload||!payload.success)return fail(payload&&payload.message);var d=payload.data||{},e=d.event||{};current={data:d,event:e};document.title=(e.Title||'Adventure')+' Registration | IWP Community Connections';var opts=attendanceOptions(e),res=resources(e),remaining=d.spotsRemaining,max=Number(e.MaxParticipants||0),avail=!max?'Registration is open.':Number(remaining)>0?remaining+' spot'+(Number(remaining)===1?'':'s')+' remaining.':bool(e.WaitlistEnabled)?'Adventure full; waitlist available.':'Adventure is full.';
root.innerHTML='<div class="registration-shell"><section class="registration-hero">'+(e.ImageUrl?'<img src="'+esc(image(e.ImageUrl))+'" alt="">':'')+'<div class="registration-hero-copy"><small>Adventure Registration</small><h1>'+esc(e.Title||'Community Adventure')+'</h1><div class="registration-meta"><span>'+esc(dateRange(e))+'</span><span>'+esc(time(e.StartTime)+(e.EndTime?' – '+time(e.EndTime):''))+'</span><span>'+esc(e.LocationName||'Location coming soon')+'</span><span>'+esc(cost(e))+'</span></div><div class="availability">'+esc(avail)+'</div></div></section><form id="regForm" class="registration-card"><div id="error" class="error hidden" role="alert" aria-live="assertive"></div><div class="registration-form-intro"><strong>Reserve your spot</strong><p>Fields marked with * are required. Your information is shared with the adventure organizer for this event.</p></div><h2>Who is attending?</h2><div class="form-grid"><div class="field"><label for="name">Your name *</label><input id="name" autocomplete="name"></div><div class="field"><label for="email">Email *</label><input id="email" type="email" autocomplete="email" required></div><div class="field"><label for="phone">Phone</label><input id="phone" type="tel" autocomplete="tel"></div><div class="field"><label for="adults">Number of adults *</label><input id="adults" type="number" min="1" value="1"></div><div class="field"><label for="children">Number of children</label><input id="children" type="number" min="0" value="0" '+(!bool(e.ChildrenAllowed)?'disabled':'')+'></div></div><div id="adultNamesWrap" class="field hidden"><label for="adultNames">Additional adult names, one per line</label><textarea id="adultNames"></textarea></div><div id="childNamesWrap" class="field hidden"><label for="childNames">Child names, one per line</label><textarea id="childNames"></textarea></div><div class="form-grid"><div class="field"><label for="emergencyName">Emergency contact name</label><input id="emergencyName"></div><div class="field"><label for="emergencyPhone">Emergency contact phone</label><input id="emergencyPhone" type="tel"></div></div>'+
(opts.length?'<h2>Attendance &amp; accommodation</h2><div class="choice-grid">'+opts.map((o,i)=>'<label class="choice"><input type="radio" name="attendance" value="'+esc(o[0])+'" '+(i===0?'checked':'')+'><span>'+esc(o[1])+'</span></label>').join('')+'</div><div id="dates" class="form-grid field"><div><label for="arrival">Arrival date</label><input id="arrival" type="date" min="'+esc(dateKey(e.StartDate))+'" max="'+esc(dateKey(e.EndDate||e.StartDate))+'" value="'+esc(dateKey(e.StartDate))+'"></div><div><label for="departure">Departure date</label><input id="departure" type="date" min="'+esc(dateKey(e.StartDate))+'" max="'+esc(dateKey(e.EndDate||e.StartDate))+'" value="'+esc(dateKey(e.EndDate||e.StartDate))+'"></div></div><div id="reserved" class="form-grid hidden"><div class="field"><label for="accommodationType">Accommodation type</label><select id="accommodationType"><option value="">Select one</option><option>Cabin</option><option>Campsite</option><option>Hotel</option><option>Airbnb</option><option>Other</option></select></div><div class="field"><label for="siteNumber">Accommodation / site #</label><input id="siteNumber"></div></div>':'')+
(res.length?'<div id="resourceSection"><h2>Organizer-provided resources</h2>'+res.map(r=>'<article class="resource-card" data-id="'+esc(r.ResourceId||'')+'" data-name="'+esc(r.Name||'Resource')+'" data-behavior="'+esc(r.ReservationBehavior||'Event Day')+'"><label><input class="resource-choice" type="checkbox"> <strong>'+esc(r.Name||'Resource')+'</strong></label>'+(r.Notes?'<p class="help">'+esc(r.Notes)+'</p>':'')+'<div class="resource-periods">'+periods(r,e).map(p=>'<label><input class="resource-period" type="checkbox" value="'+esc(p)+'"> '+esc((r.ReservationBehavior==='Time Slot')?p:pretty(p))+'</label>').join('')+'</div></article>').join('')+'</div>':'')+
(bool(e.PaidEvent)?'<h2>Payment</h2><div class="field"><label for="payment">Payment method *</label><select id="payment"><option value="">Select one</option>'+(bool(e.VenmoEnabled)?'<option>Venmo</option>':'')+(bool(e.CashAppEnabled)?'<option>Cash App</option>':'')+(bool(e.CashEnabled)?'<option>Cash</option>':'')+(bool(e.PayAtEventEnabled)?'<option>Pay at Event</option>':'')+(bool(e.BuyOwnTicketsEnabled)?'<option>Buy Own Ticket</option>':'')+'</select><p class="help">'+esc(e.CostDetails||'Follow the organizer payment instructions.')+'</p></div>':'')+
'<div class="ack-section-header"><h2>Acknowledgements</h2><button id="ackAll" class="ack-all" type="button">Acknowledge All</button></div><div class="ack-list"><label><input id="ack1" type="checkbox"> <span>I understand this is a member-organized event and is not facilitated, monitored, or organized by IWP staff.</span></label><label><input id="ack2" type="checkbox"> <span>I am participating voluntarily and am responsible for my own safety.</span></label><label><input id="ack3" type="checkbox"> <span>I agree to treat all participants with courtesy, respect, and kindness.</span></label><label><input id="ack4" type="checkbox"> <span>I understand photos and videos may be taken and will notify the organizer if I prefer not to appear.</span></label>'+(bool(e.PaidEvent)?'<label><input id="ack5" type="checkbox"> <span>I understand my reservation may not be confirmed until payment is received.</span></label><label><input id="ack6" type="checkbox"> <span>I understand refunds cannot be guaranteed.</span></label>':'')+customAcks(e)+'</div><div class="field"><label for="notes">Notes for the organizer</label><textarea id="notes"></textarea></div><label class="choice"><input id="showName" type="checkbox"> <span>Show my name on the attendee list.</span></label><div class="submit-row"><a class="secondary" href="/adventure.html?id='+encodeURIComponent(e.EventId||eventId)+'">Back to Adventure</a><button id="submit" class="primary" type="submit">Complete Registration</button></div></form></div>';bind();update();}
function customAcks(e){var raw=e.CustomAcknowledgements||'';var arr=[];try{arr=Array.isArray(raw)?raw:JSON.parse(raw||'[]')}catch(_){arr=lines(raw)}return arr.map((x,i)=>{var t=typeof x==='string'?x:(x.text||x.label||'');return t?'<label><input class="custom-ack" data-text="'+esc(t)+'" type="checkbox"> <span>'+esc(t)+'</span></label>':''}).join('')}
function attendance(){var x=document.querySelector('input[name="attendance"]:checked');return x?x.value:''}
function selectedResources(){return Array.from(document.querySelectorAll('.resource-card')).map(c=>{var on=c.querySelector('.resource-choice');if(!on||!on.checked)return null;return{resourceId:c.dataset.id,name:c.dataset.name,behavior:c.dataset.behavior,periods:Array.from(c.querySelectorAll('.resource-period:checked')).map(x=>x.value),quantity:Math.max(1,+val('adults')+(+val('children')||0))}}).filter(Boolean)}
function errors(){var e=current.event,a=+val('adults')||0,ch=+val('children')||0,out=[];if(!val('name'))out.push('Name is required.');if(!val('email')&&!val('phone'))out.push('Email or phone is required.');if(a<1)out.push('At least one adult is required.');if(a>1&&lines(val('adultNames')).length!==a-1)out.push('Enter one name for each additional adult.');if(bool(e.ChildrenAllowed)&&lines(val('childNames')).length!==ch)out.push('Enter one name for each child.');if(Boolean(val('emergencyName'))!==Boolean(val('emergencyPhone')))out.push('Enter both emergency contact fields or leave both blank.');if(bool(e.PaidEvent)&&!val('payment'))out.push('Payment method is required.');['ack1','ack2','ack3','ack4'].forEach((id,i)=>{if(!chk(id))out.push('Please accept all required acknowledgements.')});if(bool(e.PaidEvent)&&(!chk('ack5')||!chk('ack6')))out.push('Please accept the payment acknowledgements.');document.querySelectorAll('.custom-ack').forEach(x=>{if(!x.checked)out.push('Please accept: '+x.dataset.text)});selectedResources().forEach(r=>{if(!r.periods.length&&r.behavior!=='Event Day')out.push('Choose at least one period for '+r.name+'.')});return out}
function update(){var a=+val('adults')||0,ch=+val('children')||0;document.getElementById('adultNamesWrap').classList.toggle('hidden',a<=1);document.getElementById('childNamesWrap').classList.toggle('hidden',ch<=0);var r=document.getElementById('reserved');if(r)r.classList.toggle('hidden',attendance()!=='Participant Reserved');var rs=document.getElementById('resourceSection');if(rs)rs.classList.toggle('hidden',attendance()!=='Organizer-Provided');}
function requiredAcks(){return Array.from(document.querySelectorAll('#ack1,#ack2,#ack3,#ack4,#ack5,#ack6,.custom-ack')).filter(x=>!x.disabled)}
function updateAckAll(){var b=document.getElementById('ackAll'),a=requiredAcks();if(!b)return;var done=a.length&&a.every(x=>x.checked);b.textContent=done?'All Acknowledged':'Acknowledge All';b.classList.toggle('is-complete',done);b.setAttribute('aria-pressed',done?'true':'false')}
function toggleAckAll(){var a=requiredAcks(),check=!a.length||!a.every(x=>x.checked);a.forEach(x=>x.checked=check);updateAckAll()}
function bind(){var f=document.getElementById('regForm');f.addEventListener('input',function(){update();updateAckAll()});f.addEventListener('change',function(){update();updateAckAll()});f.addEventListener('submit',submit);var b=document.getElementById('ackAll');if(b)b.addEventListener('click',toggleAckAll);updateAckAll()}
async function submit(ev){ev.preventDefault();var er=errors(),box=document.getElementById('error');if(er.length){box.textContent=er[0];box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth'});return}box.classList.add('hidden');var b=document.getElementById('submit');b.disabled=true;b.textContent='Submitting…';var e=current.event,single=dateKey(e.StartDate)===dateKey(e.EndDate||e.StartDate),type=attendance();var registration={name:val('name'),email:val('email'),phone:val('phone'),adultCount:val('adults'),childCount:val('children'),adultGuestNames:val('adultNames'),childNames:val('childNames'),emergencyContactName:val('emergencyName'),emergencyContactPhone:val('emergencyPhone'),paymentMethod:val('payment'),showNameOnAttendeeList:chk('showName'),acknowledgementMemberOrganized:chk('ack1'),acknowledgementVoluntary:chk('ack2'),acknowledgementRespect:chk('ack3'),acknowledgementPhotosVideos:chk('ack4'),acknowledgementPayment:chk('ack5'),acknowledgementRefund:chk('ack6'),customAcknowledgementsAccepted:JSON.stringify(Array.from(document.querySelectorAll('.custom-ack')).map(x=>({text:x.dataset.text,accepted:x.checked}))),attendanceType:type,arrivalDate:single?dateKey(e.StartDate):val('arrival'),departureDate:single?dateKey(e.EndDate||e.StartDate):val('departure'),dayVisitDate:type==='Day Visitor'?(single?dateKey(e.StartDate):val('arrival')):'',accommodationType:val('accommodationType'),accommodationSiteNumber:val('siteNumber'),resourceReservations:JSON.stringify(selectedResources()),notes:val('notes')};
try{var r=await fetch('/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:eventId,registration:registration})});var j=await r.json();if(!j.success)throw new Error(j.message||'Registration could not be submitted.');success(j.response||{})}catch(x){box.textContent=x.message||'Registration could not be submitted.';box.classList.remove('hidden');b.disabled=false;b.removeAttribute('aria-busy');b.textContent='Complete Registration'}}
function success(resp){var wait=String(resp.status||resp.registrationStatus||'').toLowerCase().includes('wait');root.innerHTML='<section class="registration-success"><div class="check">✓</div><small>Registration Submitted</small><h1>'+(wait?'You Joined the Waitlist!':'You’re Registered!')+'</h1><p>'+(wait?'The organizer will contact you if a spot becomes available.':'Your registration was submitted successfully.')+'</p>'+(wait?'':'<div class="registration-next-steps"><strong>Check your email next.</strong><p>Your confirmation email includes the adventure details and your personal event-day QR code. Keep it handy for check-in. If plans change, contact the adventure organizer using the event information in your confirmation.</p></div>')+'<h2>'+esc(current.event.Title||'Adventure')+'</h2><div class="submit-row"><a class="secondary" href="/">View More Adventures</a><a class="primary" href="/adventure.html?id='+encodeURIComponent(eventId)+'">View This Adventure</a></div></section>';scrollTo(0,0)}
function fail(m){root.innerHTML='<section class="registration-error"><h1>Registration unavailable</h1><p>'+esc(m||'This registration could not be loaded.')+'</p><a class="primary" href="/">Return Home</a></section>'}
async function load(){if(!eventId)return fail('No adventure was selected.');try{var r=await fetch('/api/registration-data?id='+encodeURIComponent(eventId),{headers:{'accept':'application/json'},cache:'no-store'});var j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Registration could not be loaded.');render(j)}catch(x){fail(x.message||'The registration service is temporarily unavailable.')}}load();})();
