const CLIENT_ID = '976851999093-8d1na61p55803iim4202s189uncggp3t.apps.googleusercontent.com';
const SESSION_DAYS = 30;
const enc = new TextEncoder();
function b64u(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function b64uText(text){return b64u(enc.encode(text));}
function fromB64u(text){text=text.replace(/-/g,'+').replace(/_/g,'/');while(text.length%4)text+='=';return atob(text);}
async function key(secret){return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
export async function issueSession(env,user){const secret=String(env.ORGANIZER_SESSION_SECRET||'');if(!secret)throw new Error('Organizer session secret is not configured.');const payload={email:user.email,name:user.name||'',picture:user.picture||'',role:user.role||'Admin',exp:Date.now()+SESSION_DAYS*86400000};const body=b64uText(JSON.stringify(payload));const sig=new Uint8Array(await crypto.subtle.sign('HMAC',await key(secret),enc.encode(body)));return {token:body+'.'+b64u(sig),expiresAt:new Date(payload.exp).toISOString(),user:payload};}
export async function verifySession(env,token){const secret=String(env.ORGANIZER_SESSION_SECRET||'');if(!secret)throw new Error('Organizer session secret is not configured.');const parts=String(token||'').split('.');if(parts.length!==2)throw new Error('Your organizer session is missing or invalid. Please sign in again.');const ok=await crypto.subtle.verify('HMAC',await key(secret),Uint8Array.from(atob(parts[1].replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(parts[1].length/4)*4,'=')),c=>c.charCodeAt(0)),enc.encode(parts[0]));if(!ok)throw new Error('Your organizer session is invalid. Please sign in again.');let p;try{p=JSON.parse(fromB64u(parts[0]));}catch(_){throw new Error('Your organizer session is invalid. Please sign in again.');}if(!p.email||Number(p.exp||0)<=Date.now())throw new Error('Your organizer session expired. Please sign in again.');const admin=await env.COMMUNITY_DB.prepare('SELECT name,email,role,active FROM admins WHERE lower(email)=lower(?) LIMIT 1').bind(p.email).first();if(!admin||Number(admin.active)!==1)throw new Error('This account is no longer approved for organizer access.');return {email:admin.email,name:admin.name||p.name||'',role:admin.role||p.role||'Admin',picture:p.picture||''};}
export async function authenticateCredential(env,credential){if(!credential)throw new Error('Google did not return a sign-in credential.');const r=await fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(credential),{headers:{accept:'application/json'}});const info=await r.json();if(!r.ok||!info.email)throw new Error('Google sign-in could not be verified.');if(String(info.aud||'')!==CLIENT_ID)throw new Error('Google sign-in was issued for a different application.');if(String(info.email_verified)!=='true')throw new Error('Google account email is not verified.');const admin=await env.COMMUNITY_DB.prepare('SELECT name,email,role,active FROM admins WHERE lower(email)=lower(?) LIMIT 1').bind(info.email).first();if(!admin||Number(admin.active)!==1)throw new Error('This Google account is not an approved Community Connections organizer.');return {email:admin.email,name:admin.name||info.name||'',picture:info.picture||'',role:admin.role||'Admin'};}
export function json(data,status=200){return Response.json(data,{status,headers:{'cache-control':'no-store'}});}
export function displayTime(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})/);if(!m)return String(v||'');let h=Number(m[1]);const min=m[2],ap=h>=12?'PM':'AM';h=h%12||12;return h+':'+min+' '+ap;}
export function peopleExpr(){return `(COALESCE(adult_count,0)+COALESCE(child_count,0))`;}
